- id: 10.1016/j.patcog.2026.113097
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0031320326000609-ga1.jpg
- id: 10.1016/j.knosys.2025.115133
- id: 10.1016/j.patcog.2025.112770
- id: 10.1109/TKDE.2025.3592126
- id: 10.1016/j.knosys.2025.113020
- id: 10.1016/j.aej.2024.11.035
- id: 10.1016/j.aej.2024.09.109
- id: 10.1016/j.patcog.2024.110317
- id: 10.1016/j.knosys.2024.111442
- id: 10.1016/j.patcog.2023.109998
- id: 10.1016/j.eswa.2023.120371
- id: 10.1007/s41095-022-0293-5
- id: 10.1016/j.knosys.2022.109549
- id: 10.1016/j.patcog.2022.108716
- id: 10.1109/TIP.2020.3036745
- id: 10.1007/s41095-020-0166-8
- id: 10.1016/j.patcog.2026.113095
- id: 10.1109/TVCG.2025.3577807
- title: Multi-scale Template Matching with Scalable Diversity Similarity in Unconstrained Environment
  authors:
    - Yi Zhang
    - Chao Zhang
    - Takuya Akashi
  publisher: The British Machine Vision Conference (BMVC)
  date: 2019-09-09
  link: https://arxiv.org/abs/1907.01150
- title: Fast Affine Template Matching over Galois Field
  authors:
    - Chao Zhang
    - Takuya Akashi
  publisher: The British Machine Vision Conference (BMVC)
  date: 2015-09-07
  link: https://www.bmva-archive.org.uk/bmvc/2015/papers/paper121/paper121.pdf
- title: Dataset Distillation via Vision-Language Category Prototype
  authors:
    - Yawen Zou
    - Guang Li
    - Duo Su
    - Zi Wang
    - Jun Yu
    - Chao Zhang
  publisher: IEEE/CVF International Conference on Computer Vision (ICCV), Highlight
  date: 2025-10-19
  link: https://github.com/zou-yawen/Dataset-Distillation-via-Vision-Language-Category-Prototype
